import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import Vuetify from 'vuetify/lib/framework';
import Vue from 'vue';

import {
    faSignInAlt,
    faSignOutAlt,
    faKey,
    faBuilding,
    faPencilAlt,
    faBoxOpen,
    faClock,
    faCog,
    faHome,
    faPlusCircle,
    faPlane,
    faExclamationCircle,
    faTruck,
    faHotel,
    faMoneyCheckAlt,
    faPeopleArrows,
    faCalendarDay,
    faEnvelope,
    faCalendarAlt,
    faPhoneAlt,
    faUser,
    faLock,
    faCheck,
    faImage,
    faFilePdf,
    faFile,
    faCheckSquare,
    faSlash,
    faCheckCircle,
    faInfoCircle,
    faArrowUp,
    faArrowDown,
    faAngleRight,
    faAngleLeft,
    faAngleDown,
    faCalculator,
    faCreditCard,
    faCaretDown,
    faCaretUp,
    faCaretRight,
    faUpload,
    faPlaneArrival,
    faPlaneDeparture,
    faTag,
    faQuestionCircle,
    faUserCircle,
    faUserCog,
    faUserPlus,
    faEye,
    faTrash,
    faEyeSlash,
    faThumbsUp,
    faPortrait,
    faUserShield,
    faMapMarkerAlt,
    faUsers,
    faUsersSlash,
    faEllipsisV,
    faDollarSign,
    faSquare,
    faDownload,
    faPaperPlane,
    faSun,
    faStar,
    faStarHalf,
    faCloud,
    faCloudRain,
    faSnowflake,
} from '@fortawesome/free-solid-svg-icons';


import {
    faFacebookSquare,
    faTwitterSquare,
    faLinkedin,
    faYoutubeSquare,
} from '@fortawesome/free-brands-svg-icons';

library.add(
    faSignInAlt,
    faSignOutAlt,
    faKey,
    faBuilding,
    faPencilAlt,
    faPhoneAlt,
    faEnvelope,
    faClock,
    faCog,
    faPlusCircle,
    faPlane,
    faPortrait,
    faTruck,
    faHotel,
    faMoneyCheckAlt,
    faPeopleArrows,
    faCalendarDay,
    faTag,
    faHome,
    faUser,
    faUserCircle,
    faUserCog,
    faCalendarAlt,
    faBoxOpen,
    faImage,
    faFilePdf,
    faFile,
    faLock,
    faCheck,
    faCheckSquare,
    faSlash,
    faCheckCircle,
    faInfoCircle,
    faExclamationCircle,
    faArrowUp,
    faArrowDown,
    faAngleRight,
    faAngleLeft,
    faAngleDown,
    faCalculator,
    faCreditCard,
    faCaretDown,
    faCaretUp,
    faCaretRight,
    faUpload,
    faPlaneArrival,
    faPlaneDeparture,
    faQuestionCircle,
    faUserPlus,
    faThumbsUp,
    faEye,
    faEyeSlash,
    faUserShield,
    faTrash,
    faMapMarkerAlt,
    faUsers,
    faUsersSlash,
    faSquare,
    faEllipsisV,
    faDollarSign,
    faDownload,
);

library.add(
    faFacebookSquare,
    faTwitterSquare,
    faLinkedin,
    faYoutubeSquare
);

Vue.component('vue-fontawesome', FontAwesomeIcon);
Vue.use(Vuetify);

export default new Vuetify({});
